baseurl = "https://labs.tomasino.org"
title = "Tomasino Labs"
languageCode = "en-us"
theme = "blank"
MetaDataFormat = "yaml"
pygmentsCodeFences = true
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
[params]
    author = "James Tomasino"
    description = "good ideas short on time"
    og_image = "/assets/images/labs.jpg"
[author]
    name = "James Tomasino"
